all: move type defer

clean cl:
	@(rm -f move type defer)

move: move.cpp
	g++ -std=c++11 -O3 move.cpp -o move

type: type.cpp
	g++ -std=c++11 -O3 type.cpp -o type

defer: defer.cpp
	g++ -std=c++11 -O3 defer.cpp -o defer
