all: tuple str struct enum vec deque list map
clean:
	rm -f tuple str struct enum vec deque list map
tuple: tuple.rs
	rustc tuple.rs
str: str.rs
	rustc str.rs
struct: struct.rs
	rustc struct.rs
enum: enum.rs
	rustc enum.rs
vec: vec.rs
	rustc vec.rs
deque: deque.rs
	rustc deque.rs
list: list.rs
	rustc list.rs
map: map.rs
	rustc map.rs
