all: trait_draw trait_debug trait fly add_dec
clean:
	rm -f trait_draw trait_debug trait fly add_dec
trait_draw: trait_draw.rs
	rustc trait_draw.rs
trait_debug: trait_debug.rs
	rustc trait_debug.rs
trait: trait.rs
	rustc trait.rs
fly: fly.rs
	rustc fly.rs
add_dec: add_dec.rs
	rustc add_dec.rs
