all: arc assert deref match mybox option1 option3 option rc static t1 t4 tt
clean:
	rm -f arc assert closure deref match mybox option1 option3 option rc static t1 t3 t4 t tt
arc: arc.rs
	rustc arc.rs
assert: assert.rs
	rustc assert.rs
closure: closure.rs
	rustc closure.rs
deref: deref.rs
	rustc deref.rs
match: match.rs
	rustc match.rs
mybox: mybox.rs
	rustc mybox.rs
option1: option1.rs
	rustc option1.rs
option3: option3.rs
	rustc option3.rs
option: option.rs
	rustc option.rs
rc: rc.rs
	rustc rc.rs
static: static.rs
	rustc static.rs
t1: t1.rs
	rustc t1.rs
t3: t3.rs
	rustc t3.rs
t4: t4.rs
	rustc t4.rs
t: t.rs
	rustc t.rs
tt: tt.rs
	rustc tt.rs
