all: mutex thread thread2 thread3 thread4 thread5
clean:
	rm -f  mutex thread thread2 thread3 thread4 thread5
mutex: mutex.rs
	rustc mutex.rs
thread: thread.rs
	rustc thread.rs
thread2: thread2.rs
	rustc thread2.rs
thread3: thread3.rs
	rustc thread3.rs
thread4: thread4.rs
	rustc thread4.rs
thread5: thread5.rs
	rustc thread5.rs

